services:
    api:
        build: .
        restart: unless-stopped
        ports:
            - '3001:3001'
        env_file: .env.production
        networks:
            - backend

    postgres:
        image: postgres:16
        container_name: movie_watchlist_postgres
        restart: unless-stopped
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: prisma
            POSTGRES_PASSWORD: prisma
            POSTGRES_DB: movie_watchlist
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - backend

networks:
    backend:

volumes:
    pgdata:
